### ISSUE TITLE
[NFT Analyzer V1 MVP] Reach Index

### ISSUE THREAD

**Issue by onthemarkdata** [charliedao-eth/NterpriseFT#5]
|Persona|Context|Question|Feature Name|Have Data?|Difficulty|Vision of Feature|Justification|
|-----|-----|-----|-----|-----|-----|-----|-----|
|Core Team |Market Recognition|How much reach do our followers have? |Reach Index|Yes|Medium|SUM followers of our followers|Addressable market, benchmark impressions|

**Comment by charliedao-eth** [comment]
Cannot be done due to limits in Twitter API (rate limit does not allow for the identification of follower screennames from a single account).
