### ISSUE TITLE
[NFT Analyzer V1 MVP] Influencer-Followers

### ISSUE THREAD

**Issue by onthemarkdata** [charliedao-eth/NterpriseFT#7]
|Persona|Context|Question|Feature Name|Have Data?|Difficulty|Vision of Feature|Justification|
|-----|-----|-----|-----|-----|-----|-----|-----|
|Core Team |Quality Community|Who is a major influencer in our community?|Influencer-Followers|Yes|Low|Followers with significant followings|community leaders|

**Comment by charliedao-eth** [comment]
Cannot be done due to limits in Twitter API (rate limit does not allow for identification of followers at scale due).
